name: glownotes
description: "A quotes app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^0.13.3  # HTTP package dependency
  flutter_cors: ^1.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/glow_notes_logo.png
    - assets/background1.jpg
    - assets/background2.jpg
    - assets/background3.jpg
